name: emergencias_movil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.5
  google_fonts: ^6.2.1        
  geolocator: ^14.0.2
  image_picker: ^1.2.1
  record: ^6.2.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  flutter_paypal: ^0.2.1
  flutter_local_notifications: ^21.0.0
  web_socket_channel: ^3.0.3
  google_maps_flutter: ^2.17.1
  connectivity_plus: ^6.0.3
  uuid: ^4.4.0
  flutter_map: ^7.0.2        # #Ciclo5 - Mapa OpenStreetMap (sin API key)
  latlong2: ^0.9.1           # #Ciclo5 - Coordenadas para flutter_map
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true